[package]
name = "tip_jar"
type = "contract"
authors = ["aztec-tip-jar"]
version = "0.1.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.0", directory="noir-projects/aztec-nr/aztec" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.0", directory="noir-projects/noir-contracts/contracts/app/token_contract" }
